<?php
function nasa_hfe_review_from_customers() {
    return array(
        'post' => array(
            'post_title' => 'HFE Reviews From Customers',
            'post_name' => 'hfe-reviews-from-customers'
        ),
        
        'post_meta' => array(
            '_elementor_data' => '[{"id":"2082dd8","elType":"container","settings":{"margin":{"unit":"px","top":"50","right":"0","bottom":"0","left":"0","isLinked":false},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"f10735b","elType":"widget","settings":{"title":"Reviews From Customers"},"elements":[],"widgetType":"heading"},{"id":"0717d11","elType":"container","settings":{"flex_direction":"row","padding":{"unit":"px","top":"20","right":"20","bottom":"20","left":"20","isLinked":false},"css_classes":"nasa-border-shadow"},"elements":[{"id":"d5a2997","elType":"container","settings":{"content_width":"full","width":{"unit":"%","size":33.33,"sizes":[]},"margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"cf5ffbd","elType":"widget","settings":{"name":"Steve Alia.","text":"By far the most comfortable clothes label I\u2019ve ever worn. Perfect for long travels."},"elements":[],"widgetType":"nasa-boot-rate"}],"isInner":true},{"id":"3565175","elType":"container","settings":{"content_width":"full","width":{"unit":"%","size":33.33,"sizes":[]},"margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"cfb8575","elType":"widget","settings":{"name":"Eric Rowen.","text":"The colors exactly what I was looking for! I would definitely order again."},"elements":[],"widgetType":"nasa-boot-rate"}],"isInner":true},{"id":"9e44fcf","elType":"container","settings":{"content_width":"full","width":{"unit":"%","size":33.33,"sizes":[]},"boxed_width":{"unit":"px","size":33.33,"sizes":[]},"margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"5d2c63e","elType":"widget","settings":{"name":"Ardell.","text":"This was my first order and I was super pleased. Quick service at a good price."},"elements":[],"widgetType":"nasa-boot-rate"}],"isInner":true}],"isInner":true}],"isInner":false}]',
            '_elementor_css' => 'a:6:{s:4:"time";i:1698160958;s:5:"fonts";a:0:{}s:5:"icons";a:0:{}s:20:"dynamic_elements_ids";a:0:{}s:6:"status";s:4:"file";i:0;s:0:"";}',
            // 'ehf_template_type' => 'custom'
        ),

        'css' => '.elementor-[inserted_id] .elementor-element.elementor-element-2082dd8{--display:flex;--background-transition:0.3s;--margin-block-start:50px;--margin-block-end:0px;--margin-inline-start:0px;--margin-inline-end:0px;--padding-block-start:0px;--padding-block-end:0px;--padding-inline-start:0px;--padding-inline-end:0px;}.elementor-[inserted_id] .elementor-element.elementor-element-0717d11{--display:flex;--flex-direction:row;--container-widget-width:initial;--container-widget-height:100%;--container-widget-flex-grow:1;--container-widget-align-self:stretch;--background-transition:0.3s;--padding-block-start:20px;--padding-block-end:20px;--padding-inline-start:20px;--padding-inline-end:20px;}.elementor-[inserted_id] .elementor-element.elementor-element-d5a2997{--display:flex;--background-transition:0.3s;--margin-block-start:0px;--margin-block-end:0px;--margin-inline-start:0px;--margin-inline-end:0px;--padding-block-start:0px;--padding-block-end:0px;--padding-inline-start:0px;--padding-inline-end:0px;}.elementor-[inserted_id] .elementor-element.elementor-element-3565175{--display:flex;--background-transition:0.3s;--margin-block-start:0px;--margin-block-end:0px;--margin-inline-start:0px;--margin-inline-end:0px;--padding-block-start:0px;--padding-block-end:0px;--padding-inline-start:0px;--padding-inline-end:0px;}.elementor-[inserted_id] .elementor-element.elementor-element-9e44fcf{--display:flex;--background-transition:0.3s;--margin-block-start:0px;--margin-block-end:0px;--margin-inline-start:0px;--margin-inline-end:0px;--padding-block-start:0px;--padding-block-end:0px;--padding-inline-start:0px;--padding-inline-end:0px;}@media(min-width:768px){.elementor-[inserted_id] .elementor-element.elementor-element-d5a2997{--width:33.33%;}.elementor-[inserted_id] .elementor-element.elementor-element-3565175{--width:33.33%;}.elementor-[inserted_id] .elementor-element.elementor-element-9e44fcf{--width:33.33%;}}'
    );
}
