<?php
function nasa_hfe_size_guide() {
    return array(
        'post' => array(
            'post_title' => 'HFE Size Guide',
            'post_name' => 'hfe-size-guide'
        ),
        
        'post_meta' => array(
            '_elementor_data' => '[{"id":"61dca42","elType":"container","settings":[],"elements":[{"id":"0eb4328","elType":"widget","settings":{"title":"Size Guide","align":"center"},"elements":[],"widgetType":"heading"},{"id":"133edf2","elType":"widget","settings":{"tabs":[{"tab_title":"DRESSES","tab_content":"<table class=\"nasa-info-size-guide\"><thead><tr><td>Size<\/td><td>Chest<\/td><td>Waist<\/td><td>Hips<\/td><\/tr><\/thead><tbody><tr><td>XS<\/td><td>34<\/td><td>28<\/td><td>34<\/td><\/tr><tr><td>S<\/td><td>36<\/td><td>30<\/td><td>36<\/td><\/tr><tr><td>M<\/td><td>38<\/td><td>32<\/td><td>38<\/td><\/tr><tr><td>L<\/td><td>40<\/td><td>34<\/td><td>40<\/td><\/tr><tr><td>XL<\/td><td>42<\/td><td>36<\/td><td>42<\/td><\/tr><tr><td>2XL<\/td><td>44<\/td><td>38<\/td><td>44<\/td><\/tr><tr><td class=\"padding-top-25 nasa-font-color\" colspan=\"4\"><p class=\"margin-bottom-0 text-center\">All measurements are in INCHES<\/p><p class=\"margin-bottom-0 text-center\">and may vary a half inch in either direction.<\/p><\/td><\/tr><\/tbody><\/table>","_id":"4e05890"},{"tab_title":"T-SHIRT","tab_content":"<table class=\"nasa-info-size-guide\"><thead><tr><td>Size<\/td><td>Chest<\/td><td>Waist<\/td><td>Hips<\/td><\/tr><\/thead><tbody><tr><td>2XS<\/td><td>32<\/td><td>26<\/td><td>32<\/td><\/tr><tr><td>XS<\/td><td>34<\/td><td>28<\/td><td>34<\/td><\/tr><tr><td>S<\/td><td>36<\/td><td>30<\/td><td>36<\/td><\/tr><tr><td>M<\/td><td>38<\/td><td>32<\/td><td>38<\/td><\/tr><tr><td>L<\/td><td>40<\/td><td>34<\/td><td>40<\/td><\/tr><tr><td>XL<\/td><td>42<\/td><td>36<\/td><td>42<\/td><\/tr><tr><td class=\"padding-top-25 nasa-font-color\" colspan=\"4\"><p class=\"margin-bottom-0 text-center\">All measurements are in INCHES<\/p><p class=\"margin-bottom-0 text-center\">and may vary a half inch in either direction.<\/p><\/td><\/tr><\/tbody><\/table>","_id":"b8ddcdc"},{"_id":"7c32a51","tab_title":"BOTTOMS","tab_content":"<table class=\"nasa-info-size-guide\"><thead><tr><td>Size<\/td><td>Chest<\/td><td>Waist<\/td><td>Hips<\/td><\/tr><\/thead><tbody><tr><td>XS<\/td><td>34<\/td><td>28<\/td><td>34<\/td><\/tr><tr><td>S<\/td><td>36<\/td><td>30<\/td><td>36<\/td><\/tr><tr><td>M<\/td><td>38<\/td><td>32<\/td><td>38<\/td><\/tr><tr><td>L<\/td><td>40<\/td><td>34<\/td><td>40<\/td><\/tr><tr><td>XL<\/td><td>42<\/td><td>36<\/td><td>42<\/td><\/tr><tr><td>2XL<\/td><td>44<\/td><td>38<\/td><td>44<\/td><\/tr><tr><td class=\"padding-top-25 nasa-font-color\" colspan=\"4\"><p class=\"margin-bottom-0 text-center\">All measurements are in INCHES<\/p><p class=\"margin-bottom-0 text-center\">and may vary a half inch in either direction.<\/p><\/td><\/tr><\/tbody><\/table>"}],"tabs_align_horizontal":"center","border_width":{"unit":"px","size":0,"sizes":[]},"tab_color":"#0201017D","tab_active_color":"#020101"},"elements":[],"widgetType":"tabs"}],"isInner":false}]',
            '_elementor_css' => 'a:6:{s:4:"time";i:1698224358;s:5:"fonts";a:0:{}s:5:"icons";a:0:{}s:20:"dynamic_elements_ids";a:0:{}s:6:"status";s:4:"file";i:0;s:0:"";}',
            // 'ehf_template_type' => 'custom'
        ),

        'css' => '.elementor-[inserted_id] .elementor-element.elementor-element-61dca42{--display:flex;--background-transition:0.3s;}.elementor-[inserted_id] .elementor-element.elementor-element-0eb4328{text-align:center;}.elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title, .elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title:before, .elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title:after, .elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-content, .elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tabs-content-wrapper{border-width:0px;}.elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title, .elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title a{color:#0201017D;}.elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title.elementor-active,.elementor-[inserted_id] .elementor-element.elementor-element-133edf2 .elementor-tab-title.elementor-active a{color:#020101;}'
    );
}
